import type { SchemaRendererTexts } from '@/models/json-schema';

export const DEFAULT_SCHEMA_TEXTS: SchemaRendererTexts = {
  noItemSchema: 'No item schema defined.',
  noItemsYet: 'No items yet. Add one below.',
  addItem: 'Add Item',
  selectTypeToAdd: 'Select type to add…',
  noConfigurableProperties: 'No configurable properties.',
  noFieldsYet: 'No fields yet. Add one below.',
  keyColumnHeader: 'Key',
  valueColumnHeader: 'Value',
  addField: 'Add Field',
  keyInputPlaceholder: 'Enter key',
  stringInputPlaceholder: 'Enter a value',
  integerInputPlaceholder: 'Enter a whole number',
  numberInputPlaceholder: 'Enter a number',
  enumSelectPlaceholder: 'Select an option',
  selectTypePlaceholder: 'Select type',
  removeItemAriaLabel: 'Remove item',
  removeFieldAriaLabel: 'Remove field',
  typeColumnHeader: 'Type',
  entryTypeString: 'String',
  entryTypeNumber: 'Number',
  entryTypeBoolean: 'Boolean',
  entryTypeNull: 'Null',
  entryTypeObject: 'Object',
  entryTypeArray: 'Array',
  entryTypeChangeWarning: 'Changing type will reset the current value.',
  booleanTrueOption: 'True',
  booleanFalseOption: 'False',
  invalidJsonError: 'Invalid JSON',
};
