name: Release Workflow

on:
  push:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: dspashynskyi/ai-dial-ci/.github/workflows/npm_release.yml@development
    secrets: inherit
    # with:
    #   platforms: "linux/amd64,linux/arm64"