name: Release Workflow

on:
  push:
    branches: [development, release-*]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/node_release.yml@4.10.0
    with:
      promote: true # HACK: skip RC phase, project does not require stabilization period before releasing stable versions
      docker-build-enabled: false
      node-version: "24"
    secrets: inherit
